
IF(SELECT COUNT(*) FROM  dbo.REPORT_OEE WHERE MENU_ID ='mnuBaoCaoTienDoSanXuat') = 0
BEGIN
INSERT INTO dbo.REPORT_OEE(MENU_ID,MENU_TEXT,MENU_ENGLISH,MENU_CHINESE,MENU_PARENT,MENU_LINE,MENU_INDEX,SHORT_KEY,DLL_NAME,CLASS_NAME,FUNCTION_NAME,CUSTUMER,NOTE,MENU_IMAGE,
PROJECT_NAME,MENU_NOTE,MENU_FONT,MENU_POSITION,MENU_TYPE,AN_HIEN)VALUES
(   N'mnuBaoCaoTienDoSanXuat',N'Báo cáo tiến độ sản xuất', N'Báo cáo tiến độ sản xuất', N'Báo cáo tiến độ sản xuất','null',   0,4,N'', '',  'frmMain', 'LoadBaoCaoTienDoSanXuat', 
N'', N'', NULL,N'',N'','',  0,   -1, 1 )
END	

IF(SELECT COUNT(*) FROM  dbo.REPORT_OEE WHERE MENU_ID ='mnuucBaocaoDoThiOEE') = 0
BEGIN
INSERT INTO dbo.REPORT_OEE(MENU_ID,MENU_TEXT,MENU_ENGLISH,MENU_CHINESE,MENU_PARENT,MENU_LINE,MENU_INDEX,SHORT_KEY,DLL_NAME,CLASS_NAME,FUNCTION_NAME,CUSTUMER,NOTE,MENU_IMAGE,
PROJECT_NAME,MENU_NOTE,MENU_FONT,MENU_POSITION,MENU_TYPE,AN_HIEN)VALUES
(   N'mnuucBaocaoDoThiOEE',N'Báo cáo đồ thị OEE', N'Báo cáo đồ thị OEE', N'Báo cáo đồ thị OEE','null',   0,5,N'', '',  'frmMain', 'LoadBaocaoDoThiOEE', 
N'', N'', NULL,N'',N'','',  0,   -1, 1)
END	