
CREATE TABLE [dbo].[MENU_OEE]
(
[ID_MENU] [bigint] NOT NULL,
[KEY_MENU] [nvarchar] (50)  NULL,
[TEN_MENU] [nvarchar] (250)  NOT NULL,
[TEN_MENU_A] [nvarchar] (250)  NULL,
[TEN_MENU_H] [nvarchar] (250)  NULL,
[MENU_PARENT] [nvarchar] (50)  NULL,
[HIDE] [bit] NULL CONSTRAINT [DF_MENU_HIDE] DEFAULT ((0)),
[BACK_COLOR] [nvarchar] (50)  NULL,
[IMG] [nvarchar] (50)  NULL,
[STT_MENU] [int] NULL,
[CONTROLS] [nvarchar] (50)  NULL,
[MENU_LINE] [int] NULL CONSTRAINT [DF_MENU_LINE] DEFAULT ((0)),
[MENU_PARAMETER] [int] NULL,
[HOT_KEY] [nvarchar] (50)  NULL,
[INACTIVE] [bit] NULL CONSTRAINT [DF_MENU_INACTIVE] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MENU_OEE] ADD CONSTRAINT [PK_MENU_OEE] PRIMARY KEY CLUSTERED ([ID_MENU]) ON [PRIMARY]
GO


CREATE TABLE [dbo].[PERMISSION]
(
[ID_PERMISSION] [bigint] NOT NULL,
[TEN_PERMISSION] [nvarchar] (200)  NULL,
[TEN_PERMISSION_A] [nvarchar] (200)  NULL,
[TEN_PERMISSION_H] [nvarchar] (200)  NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERMISSION] ADD CONSTRAINT [PK_PERMISSION] PRIMARY KEY CLUSTERED ([ID_PERMISSION]) ON [PRIMARY]
GO


CREATE TABLE [dbo].[NHOM_MENU_OEE]
(
[ID_NHOM] [bigint] NOT NULL,
[ID_MENU] [bigint] NOT NULL,
[ID_PERMISSION] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NHOM_MENU_OEE] ADD CONSTRAINT [PK_NHOM_MENU_OEE] PRIMARY KEY CLUSTERED ([ID_NHOM], [ID_MENU]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NHOM_MENU_OEE] ADD CONSTRAINT [FK_NHOM_MENU_MENU_OEE] FOREIGN KEY ([ID_MENU]) REFERENCES [dbo].[MENU] ([ID_MENU]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[NHOM_MENU_OEE] ADD CONSTRAINT [FK_NHOM_MENU_PERMISSION_OEE] FOREIGN KEY ([ID_PERMISSION]) REFERENCES [dbo].[PERMISSION] ([ID_PERMISSION]) ON UPDATE CASCADE
GO

